# Generated by Django 4.1.7 on 2023-02-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_bb_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Images'),
        ),
    ]
