# Generated by Django 4.1.7 on 2023-03-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_bb_image_rez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='image_rez',
            field=models.TextField(null=True, verbose_name='Images_rez'),
        ),
    ]
