# Generated by Django 4.1.7 on 2023-03-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_alter_bb_image_rez'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_rez', models.ImageField(null=True, upload_to='', verbose_name='Images_rez')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Опубликовано')),
            ],
        ),
        migrations.RemoveField(
            model_name='bb',
            name='image_rez',
        ),
    ]
