# Generated by Django 4.1.7 on 2023-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_delete_rez_bb_image_rez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='image_rez',
            field=models.ImageField(default='C:\\Users\\John\\Desktop\\Documents\\Ynic\\4 semac\\Neiroset\\test\\media\\1.jpg', null=True, upload_to='', verbose_name='Images_rez'),
        ),
    ]
