# Generated by Django 4.1.7 on 2023-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_alter_bb_image_rez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='image_rez',
            field=models.ImageField(null=True, upload_to='', verbose_name='Images_rez'),
        ),
    ]
