# Generated by Django 4.1.7 on 2023-03-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0013_alter_bb_image_rez'),
    ]

    operations = [
        migrations.CreateModel(
            name='rez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_rez', models.ImageField(null=True, upload_to='', verbose_name='Images_rez')),
            ],
        ),
    ]
